/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignedInRouteImport } from './routes/signed-in'
import { Route as ApiAuthReportRouteImport } from './routes/api/auth-report'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as TTaskIdRouteImport } from './routes/t.$taskId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOauthStartProviderIdRouteImport } from './routes/api/oauth-start.$providerId'
import { Route as PProjectIdIndexRouteImport } from './routes/p.$projectId.index'
import { Route as PProjectIdChatsRouteImport } from './routes/p.$projectId.chats'
import { Route as PProjectIdDecisionsRouteImport } from './routes/p.$projectId.decisions'
import { Route as PProjectIdFilesRouteImport } from './routes/p.$projectId.files'
import { Route as PProjectIdInvariantsRouteImport } from './routes/p.$projectId.invariants'
import { Route as PProjectIdMemoryRouteImport } from './routes/p.$projectId.memory'
import { Route as PProjectIdChatsIndexRouteImport } from './routes/p.$projectId.chats.index'
import { Route as PProjectIdChatsChatIdRouteImport } from './routes/p.$projectId.chats.$chatId'
import { Route as PProjectIdChatsPasteRouteImport } from './routes/p.$projectId.chats.paste'
import { Route as PProjectIdChatsUploadRouteImport } from './routes/p.$projectId.chats.upload'
import { Route as PProjectIdChatsUrlRouteImport } from './routes/p.$projectId.chats.url'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedInRoute = SignedInRouteImport.update({
  id: '/signed-in',
  path: '/signed-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthReportRoute = ApiAuthReportRouteImport.update({
  id: '/api/auth-report',
  path: '/api/auth-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const TTaskIdRoute = TTaskIdRouteImport.update({
  id: '/t/$taskId',
  path: '/t/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthStartProviderIdRoute = ApiOauthStartProviderIdRouteImport.update({
  id: '/api/oauth-start/$providerId',
  path: '/api/oauth-start/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdChatsRoute = PProjectIdChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdDecisionsRoute = PProjectIdDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdFilesRoute = PProjectIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdInvariantsRoute = PProjectIdInvariantsRouteImport.update({
  id: '/invariants',
  path: '/invariants',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdMemoryRoute = PProjectIdMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdChatsIndexRoute = PProjectIdChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdChatsRoute,
} as any)
const PProjectIdChatsChatIdRoute = PProjectIdChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => PProjectIdChatsRoute,
} as any)
const PProjectIdChatsPasteRoute = PProjectIdChatsPasteRouteImport.update({
  id: '/paste',
  path: '/paste',
  getParentRoute: () => PProjectIdChatsRoute,
} as any)
const PProjectIdChatsUploadRoute = PProjectIdChatsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => PProjectIdChatsRoute,
} as any)
const PProjectIdChatsUrlRoute = PProjectIdChatsUrlRouteImport.update({
  id: '/url',
  path: '/url',
  getParentRoute: () => PProjectIdChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signed-in': typeof SignedInRoute
  '/api/auth-report': typeof ApiAuthReportRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/t/$taskId': typeof TTaskIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth-start/$providerId': typeof ApiOauthStartProviderIdRoute
  '/p/$projectId/chats': typeof PProjectIdChatsRouteWithChildren
  '/p/$projectId/decisions': typeof PProjectIdDecisionsRoute
  '/p/$projectId/files': typeof PProjectIdFilesRoute
  '/p/$projectId/invariants': typeof PProjectIdInvariantsRoute
  '/p/$projectId/memory': typeof PProjectIdMemoryRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/chats/$chatId': typeof PProjectIdChatsChatIdRoute
  '/p/$projectId/chats/paste': typeof PProjectIdChatsPasteRoute
  '/p/$projectId/chats/upload': typeof PProjectIdChatsUploadRoute
  '/p/$projectId/chats/url': typeof PProjectIdChatsUrlRoute
  '/p/$projectId/chats/': typeof PProjectIdChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signed-in': typeof SignedInRoute
  '/api/auth-report': typeof ApiAuthReportRoute
  '/t/$taskId': typeof TTaskIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth-start/$providerId': typeof ApiOauthStartProviderIdRoute
  '/p/$projectId/decisions': typeof PProjectIdDecisionsRoute
  '/p/$projectId/files': typeof PProjectIdFilesRoute
  '/p/$projectId/invariants': typeof PProjectIdInvariantsRoute
  '/p/$projectId/memory': typeof PProjectIdMemoryRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
  '/p/$projectId/chats/$chatId': typeof PProjectIdChatsChatIdRoute
  '/p/$projectId/chats/paste': typeof PProjectIdChatsPasteRoute
  '/p/$projectId/chats/upload': typeof PProjectIdChatsUploadRoute
  '/p/$projectId/chats/url': typeof PProjectIdChatsUrlRoute
  '/p/$projectId/chats': typeof PProjectIdChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signed-in': typeof SignedInRoute
  '/api/auth-report': typeof ApiAuthReportRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/t/$taskId': typeof TTaskIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth-start/$providerId': typeof ApiOauthStartProviderIdRoute
  '/p/$projectId/chats': typeof PProjectIdChatsRouteWithChildren
  '/p/$projectId/decisions': typeof PProjectIdDecisionsRoute
  '/p/$projectId/files': typeof PProjectIdFilesRoute
  '/p/$projectId/invariants': typeof PProjectIdInvariantsRoute
  '/p/$projectId/memory': typeof PProjectIdMemoryRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/chats/$chatId': typeof PProjectIdChatsChatIdRoute
  '/p/$projectId/chats/paste': typeof PProjectIdChatsPasteRoute
  '/p/$projectId/chats/upload': typeof PProjectIdChatsUploadRoute
  '/p/$projectId/chats/url': typeof PProjectIdChatsUrlRoute
  '/p/$projectId/chats/': typeof PProjectIdChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/signed-in'
    | '/api/auth-report'
    | '/p/$projectId'
    | '/t/$taskId'
    | '/api/auth/$'
    | '/api/oauth-start/$providerId'
    | '/p/$projectId/chats'
    | '/p/$projectId/decisions'
    | '/p/$projectId/files'
    | '/p/$projectId/invariants'
    | '/p/$projectId/memory'
    | '/p/$projectId/'
    | '/p/$projectId/chats/$chatId'
    | '/p/$projectId/chats/paste'
    | '/p/$projectId/chats/upload'
    | '/p/$projectId/chats/url'
    | '/p/$projectId/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/signed-in'
    | '/api/auth-report'
    | '/t/$taskId'
    | '/api/auth/$'
    | '/api/oauth-start/$providerId'
    | '/p/$projectId/decisions'
    | '/p/$projectId/files'
    | '/p/$projectId/invariants'
    | '/p/$projectId/memory'
    | '/p/$projectId'
    | '/p/$projectId/chats/$chatId'
    | '/p/$projectId/chats/paste'
    | '/p/$projectId/chats/upload'
    | '/p/$projectId/chats/url'
    | '/p/$projectId/chats'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/signed-in'
    | '/api/auth-report'
    | '/p/$projectId'
    | '/t/$taskId'
    | '/api/auth/$'
    | '/api/oauth-start/$providerId'
    | '/p/$projectId/chats'
    | '/p/$projectId/decisions'
    | '/p/$projectId/files'
    | '/p/$projectId/invariants'
    | '/p/$projectId/memory'
    | '/p/$projectId/'
    | '/p/$projectId/chats/$chatId'
    | '/p/$projectId/chats/paste'
    | '/p/$projectId/chats/upload'
    | '/p/$projectId/chats/url'
    | '/p/$projectId/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignedInRoute: typeof SignedInRoute
  ApiAuthReportRoute: typeof ApiAuthReportRoute
  PProjectIdRoute: typeof PProjectIdRouteWithChildren
  TTaskIdRoute: typeof TTaskIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOauthStartProviderIdRoute: typeof ApiOauthStartProviderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signed-in': {
      id: '/signed-in'
      path: '/signed-in'
      fullPath: '/signed-in'
      preLoaderRoute: typeof SignedInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-report': {
      id: '/api/auth-report'
      path: '/api/auth-report'
      fullPath: '/api/auth-report'
      preLoaderRoute: typeof ApiAuthReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$taskId': {
      id: '/t/$taskId'
      path: '/t/$taskId'
      fullPath: '/t/$taskId'
      preLoaderRoute: typeof TTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth-start/$providerId': {
      id: '/api/oauth-start/$providerId'
      path: '/api/oauth-start/$providerId'
      fullPath: '/api/oauth-start/$providerId'
      preLoaderRoute: typeof ApiOauthStartProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/chats': {
      id: '/p/$projectId/chats'
      path: '/chats'
      fullPath: '/p/$projectId/chats'
      preLoaderRoute: typeof PProjectIdChatsRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/decisions': {
      id: '/p/$projectId/decisions'
      path: '/decisions'
      fullPath: '/p/$projectId/decisions'
      preLoaderRoute: typeof PProjectIdDecisionsRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/files': {
      id: '/p/$projectId/files'
      path: '/files'
      fullPath: '/p/$projectId/files'
      preLoaderRoute: typeof PProjectIdFilesRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/invariants': {
      id: '/p/$projectId/invariants'
      path: '/invariants'
      fullPath: '/p/$projectId/invariants'
      preLoaderRoute: typeof PProjectIdInvariantsRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/memory': {
      id: '/p/$projectId/memory'
      path: '/memory'
      fullPath: '/p/$projectId/memory'
      preLoaderRoute: typeof PProjectIdMemoryRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/chats/': {
      id: '/p/$projectId/chats/'
      path: '/'
      fullPath: '/p/$projectId/chats/'
      preLoaderRoute: typeof PProjectIdChatsIndexRouteImport
      parentRoute: typeof PProjectIdChatsRoute
    }
    '/p/$projectId/chats/$chatId': {
      id: '/p/$projectId/chats/$chatId'
      path: '/$chatId'
      fullPath: '/p/$projectId/chats/$chatId'
      preLoaderRoute: typeof PProjectIdChatsChatIdRouteImport
      parentRoute: typeof PProjectIdChatsRoute
    }
    '/p/$projectId/chats/paste': {
      id: '/p/$projectId/chats/paste'
      path: '/paste'
      fullPath: '/p/$projectId/chats/paste'
      preLoaderRoute: typeof PProjectIdChatsPasteRouteImport
      parentRoute: typeof PProjectIdChatsRoute
    }
    '/p/$projectId/chats/upload': {
      id: '/p/$projectId/chats/upload'
      path: '/upload'
      fullPath: '/p/$projectId/chats/upload'
      preLoaderRoute: typeof PProjectIdChatsUploadRouteImport
      parentRoute: typeof PProjectIdChatsRoute
    }
    '/p/$projectId/chats/url': {
      id: '/p/$projectId/chats/url'
      path: '/url'
      fullPath: '/p/$projectId/chats/url'
      preLoaderRoute: typeof PProjectIdChatsUrlRouteImport
      parentRoute: typeof PProjectIdChatsRoute
    }
  }
}

interface PProjectIdChatsRouteChildren {
  PProjectIdChatsChatIdRoute: typeof PProjectIdChatsChatIdRoute
  PProjectIdChatsPasteRoute: typeof PProjectIdChatsPasteRoute
  PProjectIdChatsUploadRoute: typeof PProjectIdChatsUploadRoute
  PProjectIdChatsUrlRoute: typeof PProjectIdChatsUrlRoute
  PProjectIdChatsIndexRoute: typeof PProjectIdChatsIndexRoute
}

const PProjectIdChatsRouteChildren: PProjectIdChatsRouteChildren = {
  PProjectIdChatsChatIdRoute: PProjectIdChatsChatIdRoute,
  PProjectIdChatsPasteRoute: PProjectIdChatsPasteRoute,
  PProjectIdChatsUploadRoute: PProjectIdChatsUploadRoute,
  PProjectIdChatsUrlRoute: PProjectIdChatsUrlRoute,
  PProjectIdChatsIndexRoute: PProjectIdChatsIndexRoute,
}

const PProjectIdChatsRouteWithChildren = PProjectIdChatsRoute._addFileChildren(
  PProjectIdChatsRouteChildren,
)

interface PProjectIdRouteChildren {
  PProjectIdChatsRoute: typeof PProjectIdChatsRouteWithChildren
  PProjectIdDecisionsRoute: typeof PProjectIdDecisionsRoute
  PProjectIdFilesRoute: typeof PProjectIdFilesRoute
  PProjectIdInvariantsRoute: typeof PProjectIdInvariantsRoute
  PProjectIdMemoryRoute: typeof PProjectIdMemoryRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
}

const PProjectIdRouteChildren: PProjectIdRouteChildren = {
  PProjectIdChatsRoute: PProjectIdChatsRouteWithChildren,
  PProjectIdDecisionsRoute: PProjectIdDecisionsRoute,
  PProjectIdFilesRoute: PProjectIdFilesRoute,
  PProjectIdInvariantsRoute: PProjectIdInvariantsRoute,
  PProjectIdMemoryRoute: PProjectIdMemoryRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
}

const PProjectIdRouteWithChildren = PProjectIdRoute._addFileChildren(
  PProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignedInRoute: SignedInRoute,
  ApiAuthReportRoute: ApiAuthReportRoute,
  PProjectIdRoute: PProjectIdRouteWithChildren,
  TTaskIdRoute: TTaskIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOauthStartProviderIdRoute: ApiOauthStartProviderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
